
name: Obsidian Backup

on:
  schedule:
    - cron: '0 2 * * 0'   # Weekly on Sunday at 02:00 UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Restore Google OAuth files
        shell: bash
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" | base64 --decode > credentials.json
          echo "${{ secrets.GOOGLE_TOKEN_JSON }}" | base64 --decode > token.json
      - name: Debug restored files
        run: |
             ls -l
             echo "credentials.json size:"
             wc -c credentials.json
             echo "token.json size:"
             wc -c token.json

      - name: Run backup
        env:
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python backup.py

